### ISSUE TITLE
Does this code work with version 8 SS?

### ISSUE THREAD

**Issue by instalator** [fabtesta/synology-surveillance-api-motion-mqtt-gifs#3]

**Comment by fabtesta** [comment]
Did you try it?

**Comment by instalator** [comment]
SYNO.SurveillanceStation.Event&method=List 
Returns always empty events
{
  "events": [],
  "offset": 0,
  "timestamp": "1589121631",
  "total": 0
}

**Comment by fabtesta** [comment]
![Screenshot 2020-05-11 at 10 44 39](https://user-images.githubusercontent.com/2025908/81542124-749a9a80-9374-11ea-9c29-e8cd7dc23484.png)
This is my SS version information.
Please check the config as specified in the readme file.
Double check to have configured your cameras recording settings in "motion detection" mode.
![Screenshot 2020-05-11 at 10 45 54](https://user-images.githubusercontent.com/2025908/81542266-ab70b080-9374-11ea-9d87-ebf238ed6156.png)
